# Generated by Django 3.1 on 2021-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.ManyToManyField(blank=True, default=None, related_name='_contact_friend_+', to='chatv2.Contact'),
        ),
    ]
