# Generated by Django 3.1 on 2022-01-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv2', '0003_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='/triangle.jpg', null=True, upload_to='user_images'),
        ),
    ]
