# Generated by Django 4.1.3 on 2022-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv2', '0004_auto_20220112_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.ManyToManyField(blank=True, default=None, to='chatv2.contact'),
        ),
    ]
