# Generated by Django 3.1 on 2023-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv2', '0005_alter_contact_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.ManyToManyField(blank=True, default=None, related_name='_contact_friend_+', to='chatv2.Contact'),
        ),
    ]
