# Generated by Django 3.1 on 2022-01-10 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('brief_description', models.TextField()),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=130)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='thumbnails')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=69, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 1, 11, 0, 19, 18, 763897))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.commentforum')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postforum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
