# Generated by Django 3.1 on 2022-01-12 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20220111_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 9, 18, 41, 274319)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 12, 9, 18, 41, 273316)),
        ),
    ]
