# Generated by Django 4.1.3 on 2022-11-17 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forumcomment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 20, 22, 23, 512956)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 20, 22, 23, 512956)),
        ),
    ]
