# Generated by Django 3.1 on 2023-01-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_forumcomment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 14, 23, 53, 971974)),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 17, 14, 23, 53, 970794)),
        ),
    ]
