# Generated by Django 3.1 on 2022-01-11 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20220111_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 17, 32, 751747)),
        ),
    ]
