# Generated by Django 3.1 on 2022-01-11 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20220111_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 23, 55, 38, 170298)),
        ),
    ]
