# Generated by Django 3.1 on 2022-01-12 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20220111_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='recent_work')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 9, 18, 41, 271294)),
        ),
    ]
