# Generated by Django 3.1 on 2023-01-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 14, 23, 53, 939015)),
        ),
    ]
