# Generated by Django 3.1 on 2023-01-17 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20230117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 20, 52, 9, 561594)),
        ),
    ]
