# Generated by Django 3.1 on 2023-01-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20230117_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 0, 36, 3, 690271)),
        ),
    ]
