# Generated by Django 3.1 on 2022-01-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrowGreen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
